### ISSUE TITLE
Ender Chests Config Breaks on new versions of Forge for 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [ShetiPhian/Localizations-and-Issues#293] opened 2021-02-18 03:04 UTC
Best way to explain this is look at this issue on ae2 github https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4991

Samething Happen to the EnderTanks configs as well

**Comment by ShetiPhian** [comment] 2021-02-18 19:24
For now stick with Forge 36.0.37
If this is an unintended breaking change it will be fixed after a few builds
If its is intended the cause will need to be determined (going by the AE post it might be due to empty comment lines) and fixed an every mod that has the issue, and all users of those mods would need to make their config changes again along with deleting the .bak files

**Comment by LexManos** [comment] 2021-02-19 19:50
We intentionally closed a few cases where reading configs would not have their validator run.
Which exposed some issues with mods such as AE2 writing things to config files that can't be represented in the config file.
Specifically in his case, a empty comment can't be represented, an thus gets converted to null.
However, as this is done in a correcting phase, it doesn't overwrite any valid values in the config.
So your users won't have to re-do any of their configs. You/Others just need to stop writing invalid things in your default config/spec.
Unfortunately, it can be a little tricky to track down, as I had to write a couple debug lines to find AE2's issue.
But a couple of breakpoints in the correct method in your test environment should show you what's what.

**Comment by ShetiPhian** [comment] 2021-02-20 12:53
Lex thank you for the info
 (didn't at you so you wouldn't get an nuisance ping)

Looks to have been from empty comment stings.
EnderChests, EnderTanks, and Terraqueous all had invalid empty comments, correcting those stopped the .bak files and I'm not seeing an error in the log.

@ModernGamingWorld 
New builds have been uploaded to Curse.

**Comment by ModernGamingWorld** [comment] 2021-02-20 17:05
Thank you for the quick fix

**Closed** 2021-02-22 15:36 UTC
