### ISSUE TITLE
Can't Whitelist people to my Vault

### ISSUE THREAD

**Issue by Nodai** [ShetiPhian/Localizations-and-Issues#21] opened 2017-01-03 01:07 UTC
My teammate and I can't access either of each other's vaults... The exact situation is, I made one and added him (capitalized and lowercase both after the exact case wasn't working) to the Vault whitelist and he couldn't access it. We then reversed the situation with him as the owner and myself whitelisted, to no avail...  We both have non-numerical names so if that helps. Thanks and I hope you can fix this if others had this problem! Also, there seems to be a missing feature... In a video I watched the guy was able to highlight the name of a person in the player list screen and promote that player to admin in the vault? I can't figure out any way to do that at all.  I also had to watch the video because there wasn't any documentation on how to actually use the vault concrete. I had to look through the comment section on your post, it would be much easier if it were at the top. <3 Thanks for your awesome mod! Sorry if it seems I'm dissatisfied, I'm not :3 

I'm using Multistorage 1.10.0-1.2.10.jar on Infinity Lite version 1.3.3 for Minecraft 1.10.2.

**Comment by ShetiPhian** [comment] 2017-01-04 22:00
Are you in online or offline mode?
After adding a user and reopening the gui, is the name readable or a line of numbers and letters
Clicking on the username in the list should highlight it.

"there wasn't any documentation on how to actually use the vault concrete"
Sadly all of the mods are lacking needed information, Fruzstrated and I have been working on it but are not usually available at the same time so its going slow.

**Comment by Nodai** [comment] 2017-01-04 22:43
It's on a server and a moderator has run through and verified all this with me. The names are instantly encrypted and I can't highlight it at all. I mentioned the online or offline thing to the moderator, is that a setting in the server files? He'll talk to the owner if it is.

**Comment by Nodai** [comment] 2017-01-04 22:48
Scratch that last bit, he took a look and didn't see anything in there.

**Comment by bwille53** [comment] 2017-01-04 22:48
The server itself is hooked to a bungeecord proxy but players connect with a direct IP also. Issue i was seeing wasnt that it wasn't pulling the UUID but that once you added the user, nothing could be done. couldn't remove user or promote. I'm going to see if one of the higher ups can shoot me a server log or something.

**Comment by bwille53** [comment] 2017-01-04 22:50
Also because we are running on an older modpack version 1.3.3, I will see about pushing through the latest modpack version and will respond back. Would hate to waste your time when fix is in update possibly.

**Comment by ShetiPhian** [comment] 2017-01-04 23:21
There hasn't been access list changes in a while 1.2.10 would have the latest code.

Regardless if its a uuid or a name displayed it should be clickable. SlotVaultList extends GuiSlot so when one is clicked elementClicked would be called.

I'm using Forge's username cache to change from UUID to name, if the player has been logged by it and the name is correct it should be changing back.

What color is the uuid?
Green = in name cache
Orange = name not in cache
Red = error getting uuid from access list

**Comment by Nodai** [comment] 2017-01-04 23:25
Well I can't look directly, he left his placement of the vault door on accident, but I think it was orange.

**Comment by ShetiPhian** [comment] 2017-01-05 00:10
I've ran a bunch of single player, lan, and server tests with minimal mods (one probe, tinkers, and ender io)
No issues there.

I'll move on testing the full Infinity Lite pack.

**Comment by ShetiPhian** [comment] 2017-01-05 02:59
Well it looks like I've sorted out the issue causing invalid ids to be added/created.

There is still some weirdness with that pack though.
Despite multistorage-1.10.0-1.2.13 requiring shetiphiancore-1.10.0-3.3.6 that pack loaded without issue while only having 3.3.5
Here I was trying to figure out why my packet wasn't working, while the issue was caused by something allowing the pack to load despite incorrect dependencies.

And there is still another issue your experiencing.
If the server.properties file has the online-mode set to true, and the player has logged in (doesn't need to remain online) Forge's username cache should have a record of the uuid and name.
As long as the name is typed correctly into the vault gui, the uuid will be retrieved from the cache, the name will appear in green.

The bug I was just working on only effects 'offline' ids.
Since both of you where on the server, my guess is the username cache is empty, and it shouldn't be.

**Comment by Nodai** [comment] 2017-01-05 05:21
That sounds like an accurate diagnosis... I'll leave the rest to bwille xD Not my area of expertise :P

**Comment by Nodai** [comment] 2017-01-19 02:40
bwille53 realized that it's probably because they're going through a proxy. He suggested an offline mode that just checks the player name, but admitted that it wouldn't be safe to do. Is there any sort of workaround we can enable? I'd rather it be unsafe than nothing.

**Comment by ShetiPhian** [comment] 2017-01-19 04:19
I forgot to post here that versions 1.10.0-1.2.13 & 1.11.0-1.3.2 are now available.
Using the newest core an multistorage should have things up and running.

Offline mode exists but prior to the new builds it was tied to the user cache for name lookup. This failed when the lookup was missing the player. The client now sends the username as a fall back if the server can't look it up.

Side Note:
It had been a while since I looked over the name coloring code, and I gave you the wrong information in the last post.
Green is a verified by Mojang user, Orange is an entry based on username (offline mode), Red is still a data error.

**Comment by Nodai** [comment] 2017-01-19 04:25
We're using Infinity Lite 1.5.1 (latest) with 1.10.0-1.2.12, is there a difference between 1.2.12 &13 that would effect us immediately?

**Comment by ShetiPhian** [comment] 2017-01-19 04:47
1.2.13 contains the changes for this bug.
Infinity Lite was two versions, just over a month, behind then your reported the bug.
Not sure how fast Infinity Lite normally updates but it looks like it wont be using 1.2.13 until mid February.

**Comment by Nodai** [comment] 2017-01-19 04:51
Ack that's painful! I'll see if I can talk to the modpack authors about a quick update o.0

**Comment by Elvarion** [comment] 2017-02-03 13:13
Hmm, Our server is using
- MULTISTORAGE-1.10.0-1.2.13
- SHETIPHIANCORE-1.10.0-3.3.6

And we cant get the Whitelist / Blacklist working very well at all.. Almost all names we put in the Whitelist ends up Orange. Our server is in Online mode.

If my friend places a Door down and tries to Whitelist me im Orange for him, Yet he is green. And if I add my own name I can see myself as Green. We tried adding various people to the list and only 1 of the people on the server playing is Green for the Both of us for some reason. (No Notch does not play on our Server xD)

https://gyazo.com/cf6cb9a8e920a17b9e9d94c34231f321

We are using ATlauncher, could this cause anu issues?

**Comment by ShetiPhian** [comment] 2017-02-04 20:18
It looks to be an issue with the client being unable to get another players uuid. Players at appear in green are one the client successfully retrieved info for, orange it failed and used the offline uuid instead.

I'm not sure why the client only has the data about other players sometimes, nor do I know why the two account I use for testing seems to always have the info. (running all three instances on the same machine might be the reason)

This will need to be switched over to server side; I had the client doing the name display lookup so the server didn't have to, but that fails when the client doesn't have the needed data to begin with.



About your edit:
The names appear in red because the data is missing a display name. I didn't expect the permissions to work either but it does make sense as the uuid would match.

**Comment by ShetiPhian** [comment] 2017-02-10 01:41
I've got the code done but due to work leaving me quite tired I haven't been able to do much testing.

Here is the builds if anyone wants to do some testing.
http://www.mediafire.com/file/mwdicmf951su87w/multistorage-1.10.0-1.2.16-rb1.jar
http://www.mediafire.com/file/aphl63pegea3opj/multistorage-1.11.0-1.3.5-rb1.jar

Changes:
- Moved access list name processing to the server, should fix offline uuid being used on a verified player.
- Improved username auto complete, tab will cycle through all possible names rather then always taking the first one. (shift+tab to cycle backwards)
- Orange name entries work a bit different, while it is still based on username (offline mode), they now also accept players who are verified by Mojang.
Previously if you added someone before they ever logged into the server (or if the other fixed bug happened) the name would appear orange, when the player tried to access the vault they would be denied because only a verified uuid was checked for.

**Comment by Elvarion** [comment] 2017-02-10 10:34
Should be able to get some testing done tonight, if not then tomorrow.
Will report back with my findings!

**Closed** 2017-03-21 09:31 UTC
Labels: MultiStorage
