### ISSUE TITLE
Oddball crash when loading my game

### ISSUE THREAD

**Issue by Sunconure11** [ShetiPhian/Localizations-and-Issues#216] opened 2019-05-31 20:09 UTC
https://paste.dimdev.org/afoludixuq.mccrash

I'm... not sure what's going on here.

**Comment by ShetiPhian** [comment] 2019-06-03 11:21
I should be able to fix that after work and send you a test build.

---
Reason for the crash:
To support mod added biomes I call the addFlower method.
The problem is another mod made their list unmodifiable but didn't override the method with one that does nothing, so the game tries to add a flower to an unmodifiable list and fails.

I'll add an error handler to stop the crash from any mod that does this.

The way they have that coded you may get the same crash form another mod, as any mod that tries to add a flower to that biome will have the same error.

**Comment by ShetiPhian** [comment] 2019-06-03 21:59
I wrapped the addFlower method in an error handler to prevent the crash.
It also reports the biome that the issue occurred with.

http://www.mediafire.com/file/9ymzi6su2ukys3v/terraqueous-1.12.2-1.4.18.jar/file

**Comment by Sunconure11** [comment] 2019-06-04 17:50
Of note is that I'm using JEID, which alters the biome format

**Comment by Sunconure11** [comment] 2019-06-04 18:41
The mod at faulty is The Midnight.

**Comment by ShetiPhian** [comment] 2019-06-05 12:22
I've reported it to their issue tracker.
https://github.com/Cryptic-Mushroom/The-Midnight/issues/237

**Comment by ShetiPhian** [comment] 2019-06-05 22:42
Corail31 fixed the underlining cause, and a new build of The Midnight is up on Curse:
https://minecraft.curseforge.com/projects/the-midnight/files/2720524

As for Terraqueous, due to this being an edge case that has been fixed in the other mod, I'm going to hold off pushing a build to Curse until it contains more changes.

**Closed** 2019-12-26 19:38 UTC
