### ISSUE TITLE
sharing ownership bugged?

### ISSUE THREAD

**Issue by Keridos** [ShetiPhian/Localizations-and-Issues#182] opened 2018-05-31 21:56 UTC
Some way that multiple people can access a shared private network. Would be nice for enderchests and endertanks.

**Comment by ShetiPhian** [comment] 2018-06-05 06:06
Sounds like the Team Chests/Tanks are what your after.

If you have FTB utilities you'll need to use its team interface, otherwise the vanilla team command needs to be used. (https://minecraft.gamepedia.com/Commands/team)

Once your part of a team you use an emerald instead of a diamond to put the chest/tank into team mode. (upgrade item can be changed in the config)

By default anyone can access a tank or chest, but not upgrade, move, or link a bucket/bag. Those operations are limited to the owner or team.
In the configs you can adjust the enderlink access_settings, to make them more or less restrictive.

**Comment by Keridos** [comment] 2018-06-06 15:21
is there any way to convert a private chest/tank into a team tank?

**Comment by ShetiPhian** [comment] 2018-06-06 19:01
Break the chest/tank while sneaking, this will return the diamond/emerald and a public chest/tank.

Empty the container before changing, while you won't loose anything, you'll be unable to access it without a tank/chest on the original network (color code & owner pair)

Capacity upgrades can not be transferred as they are tied to the network and not the individual blocks.

Alternatively you could rename the old network file instantly transferring everything, including capacity, to the team network.
Make sure nothing is automatically adding anything to the chests/tanks.
Save and quit the world, not need to exit Minecraft.
Go to your world save directory, inside are endertanks and enderchests folders.
Backup these folders before continuing.
Inside each of those folders rename the file with your profile id to #your_team_name.dat

If you don't know the profile id you can use Mojangs API to get it from the username
`https://api.mojang.com/users/profiles/minecraft/<username>`

**Comment by Keridos** [comment] 2018-06-07 11:48
When using the emerald it tells me I am not in a team although FTBLib shows my team. And /team config opens up the correct GUI

**Comment by ShetiPhian** [comment] 2018-06-07 15:34
-_- They have restructured FTBLib again.
Looks like FTBLib-4.2.5 is the last build that currently works.

I'll give you a test build when I have one.

**Comment by Keridos** [comment] 2018-06-07 15:35
Ok, Thanks for the quick reply 👍

**Comment by ShetiPhian** [comment] 2018-06-08 14:39
Didn't have the time to make a test build last night, but was able to this morning.
http://www.mediafire.com/file/60fnh832y703888/shetiphiancore-1.12.0-3.5.7-TESTER1.jar

Oddly a rather large bug was discovered with team tanks, and likely chests, that no one reported.
At some point they stopped loading correctly, during world load, and forgot they where part of a team. Basically deleting the emerald upgrade. I fixed the cause in ShetiPhianCore, not sure how long its existed though.

**Comment by ShetiPhian** [comment] 2018-06-12 03:55
Curse has the new build available now.
If you not using Terraqueous or Platforms, there is no need to re-download.
[Even if you are its just partial effect related]

I moved my coremod into its own embedded jar, but it doesn't load in the test build due to me missing a step in the meta-inf configuration thus causing Forge not to extract it.

**Closed by ShetiPhian** 2018-06-12 03:55 UTC
