### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by cauliflower69** [ShetiPhian/Localizations-and-Issues#107] opened 2017-09-01 07:36 UTC
Using the latest version of Radon which is using shetiphiancore-1.12.0-3.5.1 and terraqueous-1.12.0-1.4.1 we have noticed a memory leak. 

After using warmroast it appears that the issue is with your mod

http://imgur.com/a/rhZ38

**Comment by ShetiPhian** [comment] 2017-09-01 09:01
Fruzstrated had the same issue, but didn't know what mod was causing it. 

An over site has caused inefficient code resulting in server ticks to taking too long.
I've ran the profiler to pinpoint the issue, changed the code, and have been running the profiler again.
The profiler and server console are not showing an issue anymore.
I just need to let it run some more and verify the code still works as intended.

**Comment by cauliflower69** [comment] 2017-09-01 09:23
Thank you very much!

**Comment by ShetiPhian** [comment] 2017-09-01 12:59
Code fix is in 1.4.2
https://minecraft.curseforge.com/projects/terraqueous/files/2473945

Also added a config option to disable that code just in case it causes future issues / is not wanted.
Tweaks > Mobs > addHayAITasks

**Comment by cauliflower69** [comment] 2017-09-01 15:23
Thanks again for the timely fix! Much appreciated.

**Closed** 2017-09-03 20:24 UTC
